name: SwVIP
version: 1.0.0
description: VIP system
author: [SnowRunescape]
website: https://snowdev.com.br

main: br.com.snowdev.swvip.SwVIP
softdepend: [Vault]

commands:
    swvip:
        description: Shows the plugin commands.
        aliases: []
    keys:
        description: List all keys.
        aliases: []
    newkey:
        description: New key with X days for a given group.
        aliases: [gerarkey]
    deletekey:
        description: Delete one key.
        aliases: [apagarkey]
    usekey:
        description: Uses a VIP key.
        aliases: [usarkey]
    viptime:
        description: Shows the remaining time of the VIP.
        aliases: [tempovip]
    changevip:
        description: Change your VIP.
        aliases: [trocarvip]
    givevip:
        description: Give VIP, directly.
        aliases: [darvip]
    removevip:
        description: Remove a VIP from player.
        aliases: [tirarvip]